Add to navigation and try to fix room crash
java.lang.RuntimeException: Cannot find implementation for com.zeusinstitute.upiapp.AppDatabase. AppDatabase_Impl does not exist